"""add qa_runs

Revision ID: 646fe6d5c50b
Revises: 010c28c06dd9
Create Date: 2025-12-17 14:58:29.547132

"""

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import postgresql

revision = '646fe6d5c50b'
down_revision = '010c28c06dd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qa_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_message_id', sa.UUID(), nullable=False),
    sa.Column('assistant_message_id', sa.UUID(), nullable=True),
    sa.Column('llm_provider', sa.String(length=64), nullable=True),
    sa.Column('llm_model', sa.String(length=128), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('safety_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assistant_message_id'], ['messages.id'], name=op.f('fk_qa_runs_assistant_message_id_messages')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_qa_runs_session_id_sessions')),
    sa.ForeignKeyConstraint(['user_message_id'], ['messages.id'], name=op.f('fk_qa_runs_user_message_id_messages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_qa_runs'))
    )
    op.create_index(op.f('ix_qa_runs_assistant_message_id'), 'qa_runs', ['assistant_message_id'], unique=False)
    op.create_index(op.f('ix_qa_runs_session_id'), 'qa_runs', ['session_id'], unique=False)
    op.create_index(op.f('ix_qa_runs_user_message_id'), 'qa_runs', ['user_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_qa_runs_user_message_id'), table_name='qa_runs')
    op.drop_index(op.f('ix_qa_runs_session_id'), table_name='qa_runs')
    op.drop_index(op.f('ix_qa_runs_assistant_message_id'), table_name='qa_runs')
    op.drop_table('qa_runs')
    # ### end Alembic commands ###

